//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliotecaASP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAutor
    {
        public TAutor()
        {
            this.TAutor_Titulo = new HashSet<TAutor_Titulo>();
        }
    
        public long AutorID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<TAutor_Titulo> TAutor_Titulo { get; set; }
    }
}
