//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliotecaASP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIdioma
    {
        public TIdioma()
        {
            this.TTitulo = new HashSet<TTitulo>();
        }
    
        public long IdiomaID { get; set; }
        public string Idioma { get; set; }
    
        public virtual ICollection<TTitulo> TTitulo { get; set; }
    }
}
