//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliotecaASP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TObjecto_Imagen
    {
        public long ID { get; set; }
        public long TipoObjetoID { get; set; }
        public long ObjetoID { get; set; }
        public long ImagenID { get; set; }
        public int Orden { get; set; }
    
        public virtual TImagen TImagen { get; set; }
        public virtual TTipoObjeto TTipoObjeto { get; set; }
    }
}
