//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliotecaASP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTitulo
    {
        public TTitulo()
        {
            this.TAutor_Titulo = new HashSet<TAutor_Titulo>();
            this.TPersonaje_Titulo = new HashSet<TPersonaje_Titulo>();
        }
    
        public long ID { get; set; }
        public string Titulo { get; set; }
        public long AutorID { get; set; }
        public Nullable<int> Volumen { get; set; }
        public Nullable<long> IdiomaID { get; set; }
        public Nullable<long> UbicacionID { get; set; }
        public Nullable<long> FormatoID { get; set; }
        public Nullable<long> SagaID { get; set; }
        public string Sinopsis { get; set; }
        public Nullable<long> PadreID { get; set; }
        public Nullable<long> Personaje_TituloID { get; set; }
        public Nullable<int> AñoPublicacion { get; set; }
    
        public virtual ICollection<TAutor_Titulo> TAutor_Titulo { get; set; }
        public virtual TFormato TFormato { get; set; }
        public virtual TIdioma TIdioma { get; set; }
        public virtual ICollection<TPersonaje_Titulo> TPersonaje_Titulo { get; set; }
        public virtual TSaga TSaga { get; set; }
        public virtual TUbicacion TUbicacion { get; set; }
    }
}
